a = 15
b = 20
d = 40
c = 30
f = 50
k = 100
s = 200
text = "masterda uzgarish buldi "
text2 = "masterda uzgarish buldi "
text3 = "masterda uzgarish buldi "
text4 = "masterda uzgarish buldi Master "
text5 = "masterda uzgarish buldi Master "
text6 = "masterda uzgarish buldi Master "
text7 = "masterda uzgarish buldi Master "
